default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: NoteApp_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: NoteApp_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: NoteApp_production
  username: NoteApp
  password: <%= ENV['NOTEAPP_DATABASE_PASSWORD'] %>
