# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a716dcf256a30abfb93906ef27ed90a62a551c1eb1b990a7b6eba5a0736efe0f463952cc353e1419703d9df20faa7b02154cdc76b642cdda9e563e2c5d9f7173

test:
  secret_key_base: 509c4ac945c8c32a846de03450299ee3d8e59a2aa88d0409a6573c2839945a028296e5544b03bda92ea607c2026db891152f477e5366323be69d93b65bed31b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
